CREATE OR ALTER VIEW DSDN_HETHAN AS
SELECT MADN, TENDN, NGUOIDAIDIEN, EMAIL, NGAYHETHAN
FROM DOANHNGHIEP
WHERE NGAYHETHAN = CAST(GETDATE() + 3 AS DATE);
GO

create or alter view DSDN as
select MADN, TENDN, NGUOIDAIDIEN, EMAIL, NGAYHETHAN
from DOANHNGHIEP
go


SELECT * FROM DSDN
SELECT * FROM DOANHNGHIEP
INSERT INTO DOANHNGHIEP VALUES ('TMA', 'corp@tma.com.vn', '5 Orange County, USA', 'MST3748375843', 'Scarlet Johanson', '2024-07-09', 1, 1, NULL, 'tmasolutions@12345')

SELECT * FROM DSDN_HETHAN